### ISSUE TITLE
Todo - Design & Assets

### ISSUE THREAD

**Issue by aufau** [aufau/SaberMod#5]
## Overview

Some ideas require a prior graphics design and asset creation work. If you are not a coder but have some experience with computer graphics and creating other types of mods, you can make a great contribution to SaberMod here. A help in this area would be greatly appreciated. All these tasks have their counterparts in Todo - Coding issue #1 so please check it out too before starting work. In all points it is preferred to match original JK2 style.

- [ ] **Spectator HP Indicators** HP and perhaps other status (saber style) indicators attached to player models. Shown to spectators and perhaps on teammates in team based gametypes. Inspired by HUD HP indicator?

- [ ] **HUD for Duel Camera Mode** See Todo #1 for more detailed description

- [ ] **Damage Plums** Redesign damage plums. Different font, animation, colors, behaviour - anything is possible. Fonts should be high resolution too.

- [ ] **Intermission Screen** New intermission screen with mouse support. May be customized based on gametype. Currently it should contain 3 elements: Basic scrollable scoreboard, Detailed statistics scoreboard (in a tab?), map voting widget. See Todo for more details.

- [ ] **Associated Servers Widget** List of associated servers with their status (players, game state, map). Perhaps it should be similar to map voting widget? A rough mockup I've made:
![associated-servers](https://user-images.githubusercontent.com/4474909/64488523-4135c800-d249-11e9-8500-49963ddf5fc6.jpg)
